I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/police.rpy", line 42, in script
    scene bg police clue with dissovle
  File "game/police.rpy", line 42, in <module>
    scene bg police clue with dissovle
NameError: name 'dissovle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/police.rpy", line 42, in script
    scene bg police clue with dissovle
  File "/Users/maya.vasylieva/Documents/renpy-7.4.10-sdk/renpy/ast.py", line 1439, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Users/maya.vasylieva/Documents/renpy-7.4.10-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/maya.vasylieva/Documents/renpy-7.4.10-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/police.rpy", line 42, in <module>
    scene bg police clue with dissovle
NameError: name 'dissovle' is not defined

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.10.2178
Red Romance 1.0
Fri Oct 29 10:27:24 2021
